---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.6.0
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-master
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
        - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-pcidevices"
      tag: ${DRONE_BRANCH}-head
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
          - "refs/heads/release/v*"
      event:
        - push

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-pcidevices"
      tag: "${DRONE_TAG}"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
