#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests
export GHW_DISABLE_WARNINGS=true
umockdev-run -d ./tests/snapshots/all.umockdev -- go test ./pkg/... -cover -tags=test

go test -v ./tests/integration
